name: Running Workflow to generate an HTML document from a JSON file
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  convert-json-to-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Navigating to the directory containing the .json file and reading it
        run: |
          cd src/constants
          if ls *.json
            then 
              cat constants.json
          else
              echo "JSON file not found"
          fi

      - name: Convert that file using JS0N to HTML document converter
        run: |
          npm i json-into-html
          cd/src/scripts
          node scripts.js
