name: Running Test Workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
        name: displaying a console
      - run: echo "Ran this successfully"
          echo "This was consoled"
          echo "Final console"
      - name: Checking the version of installed node
        run: node -v
